const SGXIOC_GET_DCAP_QUOTE_SIZE: u64 = 0x80047307;
const SGXIOC_GEN_DCAP_QUOTE: u64 = 0xc0187308;
const SGXIOC_GET_DCAP_SUPPLEMENTAL_SIZE: u64 = 0x80047309;
const SGXIOC_VER_DCAP_QUOTE: u64 = 0xc030730a;

pub const SGX_REPORT_DATA_SIZE: usize = 64;
pub const SGX_CPUSVN_SIZE: usize = 16;
pub const SGX_CONFIGID_SIZE: usize = 64;

pub const SGX_REPORT_BODY_RESERVED1_BYTES: usize = 12;
pub const SGX_REPORT_BODY_RESERVED2_BYTES: usize = 32;
pub const SGX_REPORT_BODY_RESERVED3_BYTES: usize = 32;
pub const SGX_REPORT_BODY_RESERVED4_BYTES: usize = 42;

pub const SGX_HASH_SIZE: usize = 32;

cfg_if::cfg_if! {
  if #[cfg(target_env = "musl")] {
      pub const IOCTL_GET_DCAP_QUOTE_SIZE: i32 = SGXIOC_GET_DCAP_QUOTE_SIZE as i32;
      pub const IOCTL_GEN_DCAP_QUOTE: i32 = SGXIOC_GEN_DCAP_QUOTE as i32;
      pub const IOCTL_GET_DCAP_SUPPLEMENTAL_SIZE: i32 = SGXIOC_GET_DCAP_SUPPLEMENTAL_SIZE as i32;
      pub const IOCTL_VER_DCAP_QUOTE: i32 = SGXIOC_VER_DCAP_QUOTE as i32;
  } else {
      pub const IOCTL_GET_DCAP_QUOTE_SIZE: u64 = SGXIOC_GET_DCAP_QUOTE_SIZE;
      pub const IOCTL_GEN_DCAP_QUOTE: u64 = SGXIOC_GEN_DCAP_QUOTE;
      pub const IOCTL_GET_DCAP_SUPPLEMENTAL_SIZE: u64 = SGXIOC_GET_DCAP_SUPPLEMENTAL_SIZE;
      pub const IOCTL_VER_DCAP_QUOTE: u64 = SGXIOC_VER_DCAP_QUOTE;
  }
}
